# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
variables:

image: registry.nicolaischmid.de/jerzy/dns-tools/image:latest
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - octodns-sync --config-file config/production.yaml --doit

  environment:
    name: production
  only:
  - master

deploy:
  stage: deploy
  script:
    - octodns-sync --config-file config/production.yaml
  environment:
    name: production