# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
variables:

image: octodns/octodns:2025.04
stages:
  - test
  - deploy

test:
  stage: test
  script:
    - octodns-sync --config-file production.yaml
  except:
    - master

deploy:
  stage: deploy
  script:
    - octodns-sync --config-file production.yaml --doit

  environment:
    name: production
  only:
    - master
