providers:
  # General SPF TXT Entries
  general:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/general
    enforce_order: False

  # Private Domains
  private:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/private
    enforce_order: False

  wasc_internal:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/wasc_internal
    enforce_order: False

  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    # email: aaa662ec@opayq.com
    token: env/CLOUDFLARE_TOKEN
    update_pcent_threshold: .6
    delete_pcent_threshold: .6

zones:
  nicolaischmid.de.:
    sources:
      - general
      - private
      - wasc_internal
    targets:
      - cloudflare

  schmid.uno.:
    sources:
      - general
      - private
    targets:
      - cloudflare

  nicolaischmid.org.:
    sources:
      - general
    targets:
      - cloudflare

  nicolaischmid.com.:
    sources:
      - general
    targets:
      - cloudflare

  mansi-in-berlin.de.:
    sources:
      - general
    targets:
      - cloudflare

  polymath.page.:
    sources:
      - general
    targets:
      - cloudflare

  noll.to.:
    sources:
      - general
    targets:
      - cloudflare
