providers:

  # General SPF TXT Entries
  general:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/general

  # Private Domains
  private:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/private

  # Freelance projects
  freelance:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/freelance

  # Private projects
  private_projects:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/private_projects

  # infrastructure
  infrastructure:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/infrastructure

  wasc:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/wasc

  wasc_internal:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/wasc_internal

  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: aaa662ec@opayq.com
    token: env/CLOUDFLARE_TOKEN

zones:
  nicolais.ch.:
    sources:
      - general
      - private
      - private_projects
      - wasc_internal
      - infrastructure
    targets:
      - cloudflare

  nicolaischmid.de.:
    sources:
      - general
      - private
      - freelance
      - wasc_internal
    targets:
      - cloudflare

  schmid.uno.:
    sources:
      - general
    targets:
      - cloudflare
      