providers:
  # General SPF TXT Entries
  general:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/general

  # Private Domains
  private:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/private

  # Freelance projects
  freelance:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/freelance

  wasc_internal:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/wasc_internal

  wasc:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones/wasc

  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: aaa662ec@opayq.com
    token: env/CLOUDFLARE_TOKEN

zones:
  nicolaischmid.de.:
    sources:
      - general
      - private
      - freelance
      - wasc_internal
      - wasc
    targets:
      - cloudflare

  schmid.uno.:
    sources:
      - general
      - private
    targets:
      - cloudflare
