'':
  - type: A
    values:
      - 5.135.34.102
  - type: MX
    values:
      - priority: 25
        value: mail.nicolaischmid.de.
  - type: SPF
    value: v=spf1 mx -all

staging:
  type: A
  values:
    - 5.135.34.102