---
? ''
: - ttl: 1
    type: A
    value: 5.135.34.102
  - ttl: 1
    type: MX
    value:
      priority: 1
      value: redirect.ovh.net.
  - ttl: 1
    type: TXT
    value: google-site-verification=9kxIDge0DN4UCYfFyuMzt4imLnSKXp491NQvWEAtjgQ

cloud:
  ttl: 1
  type: CNAME
  value: cloud.nicolaischmid.de.
horizon.admin.openstack:
  ttl: 1
  type: A
  value: 46.105.160.139
horizon.internal.openstack:
  ttl: 1
  type: A
  value: 46.105.160.139
horizon.openstack:
  ttl: 1
  type: A
  value: 46.105.160.139
juju:
  ttl: 1
  type: A
  value: 5.135.34.99
maas:
  ttl: 1
  type: A
  value: 5.135.34.98
openstack:
  ttl: 1
  type: A
  value: 46.105.160.139
pilot:
  ttl: 1
  type: A
  value: 5.135.34.103
plaasch:
  ttl: 1
  type: A
  values:
  - 151.101.1.195
  - 151.101.65.195
rechner:
  ttl: 1
  type: A
  values:
  - 151.101.1.195
  - 151.101.65.195
vpn:
  ttl: 1
  type: A
  value: 46.105.160.139
wasc:
  ttl: 1
  type: A
  values:
  - 151.101.1.195
  - 151.101.65.195
