docker:
  ttl: 1
  type: A
  value: 5.135.34.97

master.ceph:
  ttl: 1
  type: A
  value: 137.74.189.198


master.kubernetes:
  ttl: 1
  type: A
  value: 46.105.160.139


node0.ceph:
  ttl: 1
  type: A
  value: 5.135.34.99

node0.kubernetes:
  ttl: 1
  type: A
  value: 5.135.34.98

node1.ceph:
  ttl: 1
  type: A
  value: 5.135.34.103
  
traefik:
  ttl: 1
  type: A
  value: 5.135.34.98

